services:
    app.elastica.index_provider.product:
        class: App\Elastica\ProductProvider
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - App\Entity\Product
        tags:
            - { name: fos_elastica.pager_provider, index: product, type: product }

    app.elastica.model_to_elastica_transformer.product:
        class: App\Elastica\ModelToElasticaProviderTransformer
        decorates: fos_elastica.model_to_elastica_transformer.product.product
        arguments:
            - '@app.elastica.model_to_elastica_transformer.product.inner'
            - '@app.elastica.index_provider.product'
            - App\Entity\Product
            - getId

# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(resolve:ES_HOST)%', port: '%env(resolve:ES_PORT)%' }
    indexes:
        product:
            types:
                product:
                    properties:
                        ean: ~
                        offers:
                            type: nested
                            properties:
                                id: {type: integer}
                                price: {type: integer}
                                companyName: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Product
                        provider:
                            service: app.elastica.index_provider.product
