services:
    app.elastica.index_provider.product:
        class: App\Elastica\ProductProvider
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - App\Entity\Product
        tags:
            - { name: fos_elastica.pager_provider, index: product, type: product }

    app.elastica.indexer.product:
        class: App\Elastica\Indexer
        arguments:
            - '@app.elastica.index_provider.product'
            - '@fos_elastica.object_persister.product.product'

    App\Job\ReindexChangedProducts:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@app.elastica.indexer.product'

# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
    clients:
        default: { host: '%env(resolve:ES_HOST)%', port: '%env(resolve:ES_PORT)%' }
    indexes:
        product:
            types:
                product:
                    properties:
                        ean: ~
                        offers:
                            type: nested
                            properties:
                                id: { type: integer }
                                price: { type: integer }
                                companyName: ~
                    persistence:
                        driver: orm
                        model: App\Entity\Product
                        listener:
                            enabled: false
                        provider:
                            service: app.elastica.index_provider.product
